--liquibase formatted sql
--changeset erik:202510131450
--comment: board table create

CREATE TABLE BOARDS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BOARD_COLUMNS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    ORDER_INDEX INT NOT NULL,
    KIND VARCHAR(7) NOT NULL,
    BOARD_ID BIGINT NOT NULL,
    CONSTRAINT BOARDS__BOARDS_COLUMNS_FK FOREIGN KEY (BOARD_ID) REFERENCES BOARDS(ID) ON DELETE CASCADE,
    CONSTRAINT ID_ORDER_UK UNIQUE (BOARD_ID, ORDER_INDEX)
);

CREATE TABLE CARDS (
   ID BIGINT PRIMARY KEY AUTO_INCREMENT,
   TITLE VARCHAR(255) NOT NULL,
   DESCRIPTION TEXT,
   BOARD_COLUMN_ID BIGINT NOT NULL,
   CONSTRAINT BOARD_COLUMNS__CARDS_FK
        FOREIGN KEY (BOARD_COLUMN_ID) REFERENCES BOARD_COLUMNS(ID)
             ON DELETE CASCADE
);

CREATE TABLE BLOCKS (
   ID BIGINT PRIMARY KEY AUTO_INCREMENT,
   BLOCKED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   BLOCK_REASON TEXT,
   UNBLOCKED_AT TIMESTAMP NULL,
   UNBLOCK_REASON TEXT NULL,
   CARD_ID BIGINT NOT NULL,
   CONSTRAINT CARDS__BLOCKS_FK
       FOREIGN KEY (CARD_ID) REFERENCES CARDS(ID)
           ON DELETE CASCADE
);


--rollback DROP TABLE BOARDS;
--rollback DROP TABLE BOARD_COLUMNS;
--rollback DROP TABLE CARDS;
--rollback DROP TABLE BLOCKS;
